aws.region=ap-south-1
aws.dynamodb.endpoint=http://localhost:4566
aws.dynamodb.tableName=global01

server.port=8080
server.servlet.context-path=/api
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
spring.devtools.restart.enabled=false
logging.level.root=INFO